routes/web.php
<?php

Route::get('userLang/{lang}', function ($lang) {
    session()->put('user_lang', $lang);
    return redirect()->back();
})->where('lang', 'ar|en');

Route::get('terms', 'HomeController@terms');
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
Route::get('/payment/{id}', 'SubjectRequestController@payment');
Route::get('/response', 'SubjectRequestController@response');
});
Route::group(['prefix' => 'admin', 'middleware' => 'auth', 'namespace' => 'Admin'], function () {
    Route::get('/', 'HomeController@index')->name('admin.home');
    Route::resource('lecture', 'LectureController');
    Route::get('subject-request', 'SubjectRequestController@index')->name('subject.request');



    Route::group(['middleware' => 'teacher'], function () {
        Route::get('review', 'HomeController@getReviews')->name('admin.review');
        Route::get('online', 'HomeController@online')->name('admin.online');
        Route::get('offline', 'HomeController@offline')->name('admin.offline');
        Route::get('subject-request/accept/{id}', 'SubjectRequestController@accept')->name('subject.accept');
        Route::get('subject-request/refuse/{id}', 'SubjectRequestController@refuse')->name('subject.refuse');

    });

    Route::group(['middleware' => 'admin'], function () {
        Route::match(['get', 'post'], '/setting', 'HomeController@setting')->name('admin.setting');
        Route::resource('student', 'StudentController');
        Route::resource('subject', 'SubjectController');
        Route::resource('education', 'EducationLevelController');
        Route::resource('slider', 'SliderController');
        Route::resource('grade', 'GradeController');
        Route::resource('relation', 'RelationController');
        Route::resource('religion', 'ReligionController');
        Route::resource('job', 'JobController');
        Route::get('student/{student}/active/', 'StudentController@active')->name('student.active');
        Route::get('student/{student}/inactive/', 'StudentController@inactive')->name('student.inactive');
        Route::resource('teacher', 'TeacherController');
        Route::resource('certificate', 'CertificateController');
        Route::resource('category', 'CategoryController');
        Route::resource('subcategory', 'SubCategoryController');
        Route::resource('package', 'PackageController');
        Route::get('teacher/{teacher}/active/', 'TeacherController@active')->name('teacher.active');
        Route::get('teacher/{teacher}/inactive/', 'TeacherController@inactive')->name('teacher.inactive');
        Route::group(['prefix' => 'landpage'], function () {
            Route::match(['get', 'post'], '/', 'LandPageController@index')->name('landpage.home');
            Route::match(['get', 'post'], '/feature', 'LandPageController@feature')->name('landpage.feature');
            Route::match(['get', 'post'], '/awesomefeature', 'LandPageController@awesomefeature')->name('landpage.awesomefeature');
            Route::match(['get', 'post'], '/about', 'LandPageController@about')->name('landpage.about');
            Route::match(['get', 'post'], '/general', 'LandPageController@general')->name('landpage.general');
            Route::get('/contact', 'LandPageController@contact')->name('landpage.contact');
            Route::get('/subscribe', 'LandPageController@subscribe')->name('landpage.subscribe');
            Route::resource('screenshot', 'ScreenshotController');
            Route::resource('team', 'TeamController');
            Route::resource('testimonials', 'TestimonialsController');
            Route::resource('faq', 'FaqController');
        });
    });
    Route::get('teacher/{teacher}/edit', 'TeacherController@edit')->name('teacher.edit');
    Route::put('teacher/{teacher}', 'TeacherController@update')->name('teacher.update');
});

Route::post('/ajax', 'AjaxController@index')->middleware('auth');
Route::get('/', 'HomeController');
Route::post('/subscribe', 'SubscribeController@subscribe');
Route::post('/contact', 'SubscribeController@contact');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/Models/Lecture.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Lecture extends Model
{
    protected $table = 'lectures';
    protected $primaryKey = 'lecture_id';
    protected $fillable = [
        'subject_id',
    ];


    public function scopeSelf($query)
    {
        return $query->where('user_id', auth()->id());
    }

    public function subject()
    {
        return $this->belongsTo(Subject::class, 'subject_id');
    }

    public function user()
    {
        return $this->belongsTo(Teacher::class, 'user_id');
    }
}

app/Http/Controllers/Admin/LectureController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\StoreLectureRequest;
use App\Models\Category;
use App\Models\Lecture;
use App\Models\SubCategory;
use App\Models\Subject;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LectureController extends Controller
{
    private $view = 'admin.lecture.';
    private $route = 'lecture.';

    public function __construct()
    {
        $this->middleware('teacher')->only(['create', 'store']);
    }

    public function index()
    {
        if (auth()->user()->role == 1) {
            $data['data'] = Lecture::with(['user', 'subject'])->paginate();
        } elseif (auth()->user()->role == 2) {
            $data['data'] = Lecture::with('subject')->Self()->paginate();
        }
        return view($this->view . 'index', $data);
    }

    public function create()
    {
        return view($this->view . 'create', ['subject' => Subject::all()]);
    }

    public function store(StoreLectureRequest $request)
    {
        $save = new Lecture($request->all());
        $save->user_id = auth()->id();
        $save->save();
        return redirect()->route($this->route . 'index');
    }

    public function show(Lecture $lecture)
    {

    }

    public function edit(Lecture $lecture)
    {
        if (auth()->user()->role != 1 && $lecture->user_id != auth()->id()) {
            abort(404);
        }
        return view($this->view . 'edit',
            [
                'data' => $lecture,
                'subject' => Subject::all()
            ]
        );
    }

    public function update(StoreLectureRequest $request, Lecture $lecture)
    {
        if (auth()->user()->role != 1 && $lecture->user_id != auth()->id()) {
            abort(404);
        }
        $lecture->update($request->all());
        return redirect()->route($this->route . 'index');
    }


    public function destroy(Lecture $lecture)
    {

    }
}

resources/views/admin/lecture/create.blade.php
@extends('layouts.master')

@section('title')
    {{ trans('admin.lecture') }}
@endsection

@section('content')
    <div class="row bg-title">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title">{{ trans('admin.lecture') }}</h4>
        </div>
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <button class="right-side-toggle waves-effect waves-light btn-info btn-circle pull-right m-l-20">
                <i class="ti-settings text-white"></i>
            </button>
            <ol class="breadcrumb">
                <li><a href="{{ route('lecture.index') }}">{{ trans('admin.lecture') }}</a></li>
                <li class="active">{{ trans('admin.add') }}</li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <h3 class="box-title m-b-0">{{ trans('admin.lecture') }}</h3>
                <p class="text-muted m-b-30 font-13"></p>

                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <form class="form-horizontal" method="post" action="{{ route('lecture.store') }}"
                      enctype="multipart/form-data">

                    {{csrf_field()}}

                    <div class="form-group">
                        <label class="col-md-12">{{ trans('admin.subject') }}</label>
                        <div class="col-md-12">
                            <select class="form-control select2" name="subject_id">
                                <option disabled value="" selected>Select</option>
                                @foreach($subject as $value)
                                    <option value="{{ $value->subject_id }}">{{ $value->subject_title }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">{{ trans('admin.submit') }}</button>
                </form>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{ asset('js/dev.js') }}"></script>
@endpush

resources/views/admin/lecture/edit.blade.php
@extends('layouts.master')

@section('title')
    {{ trans('admin.lecture') }}
@endsection

@section('content')
    <div class="row bg-title">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title">{{ trans('admin.lecture') }}</h4>
        </div>
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <button class="right-side-toggle waves-effect waves-light btn-info btn-circle pull-right m-l-20">
                <i class="ti-settings text-white"></i>
            </button>
            <ol class="breadcrumb">
                <li><a href="{{ route('lecture.index') }}">{{ trans('admin.lecture') }}</a></li>
                <li class="active">{{ trans('admin.add') }}</li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <h3 class="box-title m-b-0">{{ trans('admin.lecture') }}</h3>
                <p class="text-muted m-b-30 font-13"></p>

                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <form class="form-horizontal" method="post" action="{{ route('lecture.update',[$data->lecture_id]) }}"
                      enctype="multipart/form-data">

                    {{csrf_field()}}
                    {{ method_field('PUT') }}

                    <div class="form-group">
                        <label class="col-md-12">{{ trans('admin.subject') }}</label>
                        <div class="col-md-12">
                            <select class="form-control select2" name="subject_id">
                                <option disabled value="" selected>Select</option>
                                @foreach($subject as $value)
                                    <option {{ $value->subject_id == $data->subject_id ? 'selected' : '' }} value="{{ $value->subject_id }}">{{ $value->subject_title }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">{{ trans('admin.submit') }}</button>
                </form>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{ asset('js/dev.js') }}"></script>
@endpush

resources/views/admin/lecture/index.blade.php
@extends('layouts.master')

@section('title')
    {{ trans('admin.lecture') }}
@endsection

@section('content')
    <div class="row bg-title">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title">{{ trans('admin.lecture') }}</h4>
        </div>
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <button class="right-side-toggle waves-effect waves-light btn-info btn-circle pull-right m-l-20">
                <i class="ti-settings text-white"></i>
            </button>
            <ol class="breadcrumb">
                <li><a href="{{ route('lecture.index') }}">{{ trans('admin.lecture') }}</a></li>
                <li class="active">{{ trans('admin.show') }}</li>
            </ol>
        </div>
    </div>


    @if(auth()->user()->role==2)
        <button class="fcbtn btn btn-success btn-1d"
                onclick="window.location='{{ route('lecture.create') }}'">{{ trans('admin.add') }}</button>
        <br>
        <br>
    @endif

    <div class="row">

        <div class="col-sm-12">

            <div class="white-box">
                <h3 class="box-title m-b-0">{{ trans('admin.lecture') }}</h3>
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>#</th>
                            @if(auth()->user()->role==1)
                                <th>{{ trans('admin.name') }}</th>
                            @endif
                            <th>{{ trans('admin.subject') }}</th>
                            <th>{{ trans('admin.subject_description') }}</th>
                            <!-- <th>{{ trans('admin.subject_hours') }}</th> -->
                            @if(auth()->user()->role==2)
                                <th class="text-nowrap">{{ trans('admin.action') }}</th>
                            @endif
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($data as $key=>$value)
                            <tr>
                                <td>{{ $key+1 }}</td>
                                @if(auth()->user()->role==1)
                                    <td>{{ $value->user->name }}</td>
                                @endif
                                <td width="200px">{{ $value->subject->subject_title }}</td>
                                <td width="500px">{{ $value->subject->subject_description }}</td>
                                <!-- <td width="20px">{{ $value->subject->subject_hour }}</td> -->
                                @if(auth()->user()->role==2)

                                    <td class="text-nowrap">

                                        <a href="{{ route('lecture.edit',[$value->lecture_id]) }}"
                                           data-toggle="tooltip"
                                           data-original-title="Edit">
                                            <i class="fa fa-pencil text-inverse m-r-10"></i>
                                        </a>

                                        {{--<a href=""--}}
                                        {{--onclick=" event.preventDefault();--}}
                                        {{--var r = confirm('are you sure?');--}}
                                        {{--if (r==true){document.getElementById('delete{{$value->lecture_id}}').submit();}"--}}
                                        {{--data-toggle="tooltip" data-original-title="Close">--}}
                                        {{--<i class="fa fa-close text-danger"></i>--}}
                                        {{--</a>--}}

                                        {{--<form method="post"--}}
                                        {{--id="delete{{$value->lecture_id}}"--}}
                                        {{--action="{{ route('lecture.destroy',[$value->lecture_id]) }}"--}}
                                        {{--style="display: none;">--}}
                                        {{--<input name="_method" type="hidden" value="DELETE">--}}
                                        {{--{{ csrf_field() }}--}}
                                        {{--</form>--}}
                                    </td>
                                @endif
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{ $data->links() }}
                </div>
            </div>
        </div>
    </div>


@endsection