routes/web.php
<?php

Route::get('userLang/{lang}', function ($lang) {
    session()->put('user_lang', $lang);
    return redirect()->back();
})->where('lang', 'ar|en');

Route::get('terms', 'HomeController@terms');
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
Route::get('/payment/{id}', 'SubjectRequestController@payment');
Route::get('/response', 'SubjectRequestController@response');
});
Route::group(['prefix' => 'admin', 'middleware' => 'auth', 'namespace' => 'Admin'], function () {
    Route::get('/', 'HomeController@index')->name('admin.home');
    Route::resource('lecture', 'LectureController');
    Route::get('subject-request', 'SubjectRequestController@index')->name('subject.request');



    Route::group(['middleware' => 'teacher'], function () {
        Route::get('review', 'HomeController@getReviews')->name('admin.review');
        Route::get('online', 'HomeController@online')->name('admin.online');
        Route::get('offline', 'HomeController@offline')->name('admin.offline');
        Route::get('subject-request/accept/{id}', 'SubjectRequestController@accept')->name('subject.accept');
        Route::get('subject-request/refuse/{id}', 'SubjectRequestController@refuse')->name('subject.refuse');

    });

    Route::group(['middleware' => 'admin'], function () {
        Route::match(['get', 'post'], '/setting', 'HomeController@setting')->name('admin.setting');
        Route::resource('student', 'StudentController');
        Route::resource('subject', 'SubjectController');
        Route::resource('education', 'EducationLevelController');
        Route::resource('slider', 'SliderController');
        Route::resource('grade', 'GradeController');
        Route::resource('relation', 'RelationController');
        Route::resource('religion', 'ReligionController');
        Route::resource('job', 'JobController');
        Route::get('student/{student}/active/', 'StudentController@active')->name('student.active');
        Route::get('student/{student}/inactive/', 'StudentController@inactive')->name('student.inactive');
        Route::resource('teacher', 'TeacherController');
        Route::resource('certificate', 'CertificateController');
        Route::resource('category', 'CategoryController');
        Route::resource('subcategory', 'SubCategoryController');
        Route::resource('package', 'PackageController');
        Route::get('teacher/{teacher}/active/', 'TeacherController@active')->name('teacher.active');
        Route::get('teacher/{teacher}/inactive/', 'TeacherController@inactive')->name('teacher.inactive');
        Route::group(['prefix' => 'landpage'], function () {
            Route::match(['get', 'post'], '/', 'LandPageController@index')->name('landpage.home');
            Route::match(['get', 'post'], '/feature', 'LandPageController@feature')->name('landpage.feature');
            Route::match(['get', 'post'], '/awesomefeature', 'LandPageController@awesomefeature')->name('landpage.awesomefeature');
            Route::match(['get', 'post'], '/about', 'LandPageController@about')->name('landpage.about');
            Route::match(['get', 'post'], '/general', 'LandPageController@general')->name('landpage.general');
            Route::get('/contact', 'LandPageController@contact')->name('landpage.contact');
            Route::get('/subscribe', 'LandPageController@subscribe')->name('landpage.subscribe');
            Route::resource('screenshot', 'ScreenshotController');
            Route::resource('team', 'TeamController');
            Route::resource('testimonials', 'TestimonialsController');
            Route::resource('faq', 'FaqController');
        });
    });
    Route::get('teacher/{teacher}/edit', 'TeacherController@edit')->name('teacher.edit');
    Route::put('teacher/{teacher}', 'TeacherController@update')->name('teacher.update');
});

Route::post('/ajax', 'AjaxController@index')->middleware('auth');
Route::get('/', 'HomeController');
Route::post('/subscribe', 'SubscribeController@subscribe');
Route::post('/contact', 'SubscribeController@contact');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/Models/Religion.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Religion extends Model
{
    protected $table = 'religions';
    protected $primaryKey = 'religion_id';
    protected $fillable = [
        'religion_name',
        'religion_name_english',
    ];
}

app/Http/Controllers/Admin/ReligionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Religion;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ReligionController extends Controller
{
    private $view = 'admin.religion.';
    private $route = 'religion.';

    public function index()
    {
        return view($this->view . 'index', ['data' => Religion::paginate()]);
    }

    public function create()
    {
        return view($this->view . 'create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'religion_name' => 'required|max:190',
            'religion_name_english' => 'required|max:190',
        ]);

        (new Religion($request->all()))->save();
        return redirect()->route($this->route . 'index');
    }

    public function show(Religion $grade)
    {

    }

    public function edit(Religion $religion)
    {
        return view($this->view . 'edit', ['data' => $religion]);
    }

    public function update(Request $request, Religion $religion)
    {
        $this->validate($request, [
            'religion_name' => 'required|max:190',
            'religion_name_english' => 'required|max:190',
        ]);
        $religion->update($request->all());
        return redirect()->route($this->route . 'index');
    }

    public function destroy(Religion $religion)
    {
        $religion->delete();
        return redirect()->route($this->route . 'index');
    }
}

resources/views/admin/religion/create.blade.php
@extends('layouts.master')

@section('title')
    {{ trans('admin.religion') }}
@endsection

@section('content')
    <div class="row bg-title">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title">{{ trans('admin.religion') }}</h4>
        </div>
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <button class="right-side-toggle waves-effect waves-light btn-info btn-circle pull-right m-l-20">
                <i class="ti-settings text-white"></i>
            </button>
            <ol class="breadcrumb">
                <li><a href="{{ route('religion.index') }}">{{ trans('admin.religion') }}</a></li>
                <li class="active">{{ trans('admin.add') }}</li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <h3 class="box-title m-b-0">{{ trans('admin.religion') }}</h3>
                <p class="text-muted m-b-30 font-13"></p>

                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <form class="form-horizontal" method="post" action="{{ route('religion.store') }}"
                      enctype="multipart/form-data">

                    {{csrf_field()}}

                    <div class="form-group">
                        <label class="col-md-12">{{ trans('admin.name') }}</label>
                        <div class="col-md-12">
                            <input type="text" value="{{ old('religion_name') }}" class="form-control" name="religion_name">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-12">{{ trans('admin.name_english') }}</label>
                        <div class="col-md-12">
                            <input type="text" value="{{ old('religion_name_english') }}" class="form-control" name="religion_name_english">
                        </div>
                    </div>

                    <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">{{ trans('admin.submit') }}</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/religion/edit.blade.php
@extends('layouts.master')

@section('title')
    {{ trans('admin.religion') }}
@endsection

@section('content')
    <div class="row bg-title">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title">{{ trans('admin.religion') }}</h4>
        </div>
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <button class="right-side-toggle waves-effect waves-light btn-info btn-circle pull-right m-l-20">
                <i class="ti-settings text-white"></i>
            </button>
            <ol class="breadcrumb">
                <li><a href="{{ route('religion.index') }}">{{ trans('admin.religion') }}</a></li>
                <li class="active">{{ trans('admin.add') }}</li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <h3 class="box-title m-b-0">{{ trans('admin.religion') }}</h3>
                <p class="text-muted m-b-30 font-13"></p>

                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <form class="form-horizontal" method="post"
                      action="{{ route('religion.update',[$data->religion_id]) }}"
                      enctype="multipart/form-data">

                    {{ csrf_field() }}
                    {{ method_field('PUT') }}

                    <div class="form-group">
                        <label class="col-md-12">{{ trans('admin.name') }}</label>
                        <div class="col-md-12">
                            <input type="text" value="{{ old('religion_name',$data->religion_name) }}"
                                   class="form-control" name="religion_name">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-12">{{ trans('admin.name_english') }}</label>
                        <div class="col-md-12">
                            <input type="text" value="{{ old('religion_name_english',$data->religion_name_english) }}"
                                   class="form-control" name="religion_name_english">
                        </div>
                    </div>

                    <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">{{ trans('admin.submit') }}</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/religion/index.blade.php
@extends('layouts.master')

@section('title')
    {{ trans('admin.religion') }}
@endsection

@section('content')
    <div class="row bg-title">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title">{{ trans('admin.religion') }}</h4>
        </div>
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <button class="right-side-toggle waves-effect waves-light btn-info btn-circle pull-right m-l-20">
                <i class="ti-settings text-white"></i>
            </button>
            <ol class="breadcrumb">
                <li><a href="{{ route('religion.index') }}">{{ trans('admin.religion') }}</a></li>
                <li class="active">{{ trans('admin.show') }}</li>
            </ol>
        </div>
    </div>

    <button class="fcbtn btn btn-success btn-1d"
            onclick="window.location='{{ route('religion.create') }}'">{{ trans('admin.add') }}</button>
    <br>
    <br>

    <div class="row">

        <div class="col-sm-12">

            <div class="white-box">
                <h3 class="box-title m-b-0">{{ trans('admin.religion') }}</h3>
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>{{ trans('admin.name') }}</th>
                            <th>{{ trans('admin.name_english') }}</th>
                            <th class="text-nowrap">{{ trans('admin.action') }}</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($data as $key=>$value)
                            <tr>
                                <td>{{ $key+1 }}</td>
                                <td>{{ $value->religion_name }}</td>
                                <td>{{ $value->religion_name_english }}</td>
                                <td class="text-nowrap">

                                    <a href="{{ route('religion.edit',[$value->religion_id]) }}"
                                       data-toggle="tooltip"
                                       data-original-title="Edit">
                                        <i class="fa fa-pencil text-inverse m-r-10"></i>
                                    </a>

                                    <a href=""
                                       onclick=" event.preventDefault();
                                               var r = confirm('are you sure?');
                                               if (r==true){document.getElementById('delete{{$value->religion_id}}').submit();}"
                                       data-toggle="tooltip" data-original-title="Close">
                                        <i class="fa fa-close text-danger"></i>
                                    </a>

                                    <form method="post"
                                          id="delete{{$value->religion_id}}"
                                          action="{{ route('religion.destroy',[$value->religion_id]) }}"
                                          style="display: none;">
                                        <input name="_method" type="hidden" value="DELETE">
                                        {{ csrf_field() }}
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{ $data->links() }}
                </div>
            </div>
        </div>
    </div>


@endsection