routes/web.php
<?php

Route::get('userLang/{lang}', function ($lang) {
    session()->put('user_lang', $lang);
    return redirect()->back();
})->where('lang', 'ar|en');

Route::get('terms', 'HomeController@terms');
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
Route::get('/payment/{id}', 'SubjectRequestController@payment');
Route::get('/response', 'SubjectRequestController@response');
});
Route::group(['prefix' => 'admin', 'middleware' => 'auth', 'namespace' => 'Admin'], function () {
    Route::get('/', 'HomeController@index')->name('admin.home');
    Route::resource('lecture', 'LectureController');
    Route::get('subject-request', 'SubjectRequestController@index')->name('subject.request');



    Route::group(['middleware' => 'teacher'], function () {
        Route::get('review', 'HomeController@getReviews')->name('admin.review');
        Route::get('online', 'HomeController@online')->name('admin.online');
        Route::get('offline', 'HomeController@offline')->name('admin.offline');
        Route::get('subject-request/accept/{id}', 'SubjectRequestController@accept')->name('subject.accept');
        Route::get('subject-request/refuse/{id}', 'SubjectRequestController@refuse')->name('subject.refuse');

    });

    Route::group(['middleware' => 'admin'], function () {
        Route::match(['get', 'post'], '/setting', 'HomeController@setting')->name('admin.setting');
        Route::resource('student', 'StudentController');
        Route::resource('subject', 'SubjectController');
        Route::resource('education', 'EducationLevelController');
        Route::resource('slider', 'SliderController');
        Route::resource('grade', 'GradeController');
        Route::resource('relation', 'RelationController');
        Route::resource('religion', 'ReligionController');
        Route::resource('job', 'JobController');
        Route::get('student/{student}/active/', 'StudentController@active')->name('student.active');
        Route::get('student/{student}/inactive/', 'StudentController@inactive')->name('student.inactive');
        Route::resource('teacher', 'TeacherController');
        Route::resource('certificate', 'CertificateController');
        Route::resource('category', 'CategoryController');
        Route::resource('subcategory', 'SubCategoryController');
        Route::resource('package', 'PackageController');
        Route::get('teacher/{teacher}/active/', 'TeacherController@active')->name('teacher.active');
        Route::get('teacher/{teacher}/inactive/', 'TeacherController@inactive')->name('teacher.inactive');
        Route::group(['prefix' => 'landpage'], function () {
            Route::match(['get', 'post'], '/', 'LandPageController@index')->name('landpage.home');
            Route::match(['get', 'post'], '/feature', 'LandPageController@feature')->name('landpage.feature');
            Route::match(['get', 'post'], '/awesomefeature', 'LandPageController@awesomefeature')->name('landpage.awesomefeature');
            Route::match(['get', 'post'], '/about', 'LandPageController@about')->name('landpage.about');
            Route::match(['get', 'post'], '/general', 'LandPageController@general')->name('landpage.general');
            Route::get('/contact', 'LandPageController@contact')->name('landpage.contact');
            Route::get('/subscribe', 'LandPageController@subscribe')->name('landpage.subscribe');
            Route::resource('screenshot', 'ScreenshotController');
            Route::resource('team', 'TeamController');
            Route::resource('testimonials', 'TestimonialsController');
            Route::resource('faq', 'FaqController');
        });
    });
    Route::get('teacher/{teacher}/edit', 'TeacherController@edit')->name('teacher.edit');
    Route::put('teacher/{teacher}', 'TeacherController@update')->name('teacher.update');
});

Route::post('/ajax', 'AjaxController@index')->middleware('auth');
Route::get('/', 'HomeController');
Route::post('/subscribe', 'SubscribeController@subscribe');
Route::post('/contact', 'SubscribeController@contact');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

resources/views/partial/navbar.blade.php
<nav class="navbar navbar-default navbar-static-top m-b-0">
    <div class="navbar-header">
        <div class="top-left-part">
            <!-- Logo -->
            <a class="logo" href="index.html">
                <b>
                    <img src="{{ asset('assets') }}/plugins/images/admin-logo.png"
                         alt="home" class="dark-logo"/>
                    <img src="{{ asset('assets') }}/plugins/images/admin-logo-dark.png" alt="home"
                         class="light-logo"/>
                </b>
                <span class="hidden-xs">
                        <img src="{{ asset('assets') }}/plugins/images/admin-text.png"
                             alt="home" class="dark-logo"/>
                    <img src="{{ asset('assets') }}/plugins/images/admin-text-dark.png" alt="home"
                         class="light-logo"/>
                     </span> </a>
        </div>

        <ul class="nav navbar-top-links navbar-left">
            <li><a href="javascript:void(0)" class="open-close waves-effect waves-light"><i class="ti-menu"></i></a>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle waves-effect waves-light" data-toggle="dropdown" href="#"> <i
                            class="mdi mdi-gmail"></i>
                    <div class="notify"><span class="heartbit"></span> <span class="point"></span></div>
                </a>
                <ul class="dropdown-menu mailbox animated bounceInDown">
                    <li>
                        <div class="drop-title">You have 4 new messages</div>
                    </li>
                    <li>
                        <div class="message-center">
                            <a href="#">
                                <div class="user-img"><img
                                            src="{{ asset('assets') }}/plugins/images/users/pawandeep.jpg"
                                            alt="user" class="img-circle"> <span
                                            class="profile-status online pull-right"></span></div>
                                <div class="mail-contnet">
                                    <h5>Pavan kumar</h5> <span class="mail-desc">Just see the my admin!</span> <span
                                            class="time">9:30 AM</span></div>
                            </a>
                            <a href="#">
                                <div class="user-img"><img src="{{ asset('assets') }}/plugins/images/users/sonu.jpg"
                                                           alt="user" class="img-circle"> <span
                                            class="profile-status busy pull-right"></span></div>
                                <div class="mail-contnet">
                                    <h5>Sonu Nigam</h5> <span class="mail-desc">I've sung a song! See you at</span>
                                    <span class="time">9:10 AM</span></div>
                            </a>
                            <a href="#">
                                <div class="user-img"><img
                                            src="{{ asset('assets') }}/plugins/images/users/arijit.jpg" alt="user"
                                            class="img-circle"> <span class="profile-status away pull-right"></span>
                                </div>
                                <div class="mail-contnet">
                                    <h5>Arijit Sinh</h5> <span class="mail-desc">I am a singer!</span> <span
                                            class="time">9:08 AM</span></div>
                            </a>
                            <a href="#">
                                <div class="user-img"><img
                                            src="{{ asset('assets') }}/plugins/images/users/pawandeep.jpg"
                                            alt="user" class="img-circle"> <span
                                            class="profile-status offline pull-right"></span></div>
                                <div class="mail-contnet">
                                    <h5>Pavan kumar</h5> <span class="mail-desc">Just see the my admin!</span> <span
                                            class="time">9:02 AM</span></div>
                            </a>
                        </div>
                    </li>
                    <li>
                        <a class="text-center" href="javascript:void(0);"> <strong>See all notifications</strong> <i
                                    class="fa fa-angle-right"></i> </a>
                    </li>
                </ul>
                <!-- /.dropdown-messages -->
            </li>
            <!-- .Task dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle waves-effect waves-light" data-toggle="dropdown" href="#"> <i
                            class="mdi mdi-check-circle"></i>
                    <div class="notify"><span class="heartbit"></span><span class="point"></span></div>
                </a>
                <ul class="dropdown-menu dropdown-tasks animated slideInUp">
                    <li>
                        <a href="#">
                            <div>
                                <p><strong>Task 1</strong> <span class="pull-right text-muted">40% Complete</span>
                                </p>
                                <div class="progress progress-striped active">
                                    <div class="progress-bar progress-bar-success" role="progressbar"
                                         aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"
                                         style="width: 40%"><span class="sr-only">40% Complete (success)</span>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <p><strong>Task 2</strong> <span class="pull-right text-muted">20% Complete</span>
                                </p>
                                <div class="progress progress-striped active">
                                    <div class="progress-bar progress-bar-info" role="progressbar"
                                         aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"
                                         style="width: 20%"><span class="sr-only">20% Complete</span></div>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <p><strong>Task 3</strong> <span class="pull-right text-muted">60% Complete</span>
                                </p>
                                <div class="progress progress-striped active">
                                    <div class="progress-bar progress-bar-warning" role="progressbar"
                                         aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"
                                         style="width: 60%"><span class="sr-only">60% Complete (warning)</span>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <p><strong>Task 4</strong> <span class="pull-right text-muted">80% Complete</span>
                                </p>
                                <div class="progress progress-striped active">
                                    <div class="progress-bar progress-bar-danger" role="progressbar"
                                         aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"
                                         style="width: 80%"><span class="sr-only">80% Complete (danger)</span></div>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a class="text-center" href="#"> <strong>See All Tasks</strong> <i
                                    class="fa fa-angle-right"></i> </a>
                    </li>
                </ul>
            </li>

        </ul>

        <ul class="nav navbar-top-links navbar-right pull-right">
            <li>
                <form role="search" class="app-search hidden-sm hidden-xs m-r-10">
                    <input type="text" placeholder="{{ trans('admin.search') }}..." class="form-control"> <a href=""><i
                                class="fa fa-search"></i></a></form>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#">
                    <img src="{{ asset('assets') }}/plugins/images/users/varun.jpg" alt="user-img" width="36"
                         class="img-circle">
                    <b class="hidden-xs">{{ auth()->user()->name }}</b>
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu dropdown-user animated flipInY">
                    <li>
                        <div class="dw-user-box">
                            <div class="u-img"><img src="{{ asset('assets') }}/plugins/images/users/varun.jpg"
                                                    alt="user"/></div>
                            <div class="u-text">
                                <h4>{{ auth()->user()->name }}</h4>
                                <p class="text-muted">
                                    {{ auth()->user()->email }}
                                </p>
                                <a href="{{ route('admin.home') }}" class="btn btn-rounded btn-danger btn-sm">
                                    {{ trans('admin.View_Profile') }}
                                </a>

                                @if(auth()->user()->online==1)
                                    <a href="{{ route('admin.offline') }}" class="btn btn-rounded btn-danger btn-sm">
                                        {{ trans('admin.Go_Offline') }}
                                    </a>
                                @else
                                    <a href="{{ route('admin.online') }}" class="btn btn-rounded btn-success btn-sm">
                                        {{ trans('admin.Go_Online') }}
                                    </a>
                                @endif

                                @if(session()->get('user_lang')=='ar')
                                    <a href="{{ url('userLang/en') }}" class="btn btn-rounded btn-danger btn-sm">
                                        {{ __('admin.english') }}
                                    </a>
                                @else
                                    <a href="{{ url('userLang/ar') }}" class="btn btn-rounded btn-success btn-sm">
                                        {{ __('admin.arabic') }}
                                    </a>
                                @endif
                            </div>
                        </div>
                    </li>
                    <li role="separator" class="divider"></li>

                    <li>
                        <a href="{{ route('admin.home') }}">
                            <i class="ti-user"></i>{{ trans('admin.my_profile') }} 
                        </a>
                    </li>

                    <li><a href="#"><i class="ti-wallet"></i>{{ trans('admin.my_balance') }} </a></li>
                    <li><a href="#"><i class="ti-email"></i> {{ trans('admin.inbox') }}</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#"><i class="ti-settings"></i>{{ trans('admin.account_setting') }} </a></li>
                    <li role="separator" class="divider"></li>

                    <li>
                        <a href="" onclick=" event.preventDefault(); document.getElementById('logout-form').submit();">
                            <i class="fa fa-power-off"></i>{{ trans('admin.logout') }} 
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST"
                              style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</nav>

resources/views/partial/sidebar.blade.php
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav slimscrollsidebar">

        <div class="sidebar-head">
            <h3>
                <span class="fa-fw open-close"><i class="ti-close ti-menu"></i></span>
                <span class="hide-menu">Navigation</span>
            </h3>
        </div>

        <ul class="nav" id="side-menu">
            <li>
                <a href="{{ route('admin.home') }}" class="waves-effect">
                    <i class="ti-user fa-fw"></i>
                    <span class="hide-menu">{{ trans('admin.profile') }}</span>
                </a>
            </li>

            <li>
                <a href="{{ route('lecture.index') }}" class="">
                    <i class="mdi mdi-settings fa-fw"></i>
                    <span class="">{{ trans('admin.lecture') }}</span>
                </a>
            </li>

            <li>
                <a href="{{ route('subject.request') }}" class="">
                    <i class="mdi mdi-settings fa-fw"></i>
                    <span class="">{{ trans('admin.subject_request') }}</span>
                </a>
            </li>

            @if(auth()->user()->role==2)
                <li>
                    <a href="{{ route('admin.review') }}" class="">
                        <i class="mdi mdi-settings fa-fw"></i>
                        <span class="">{{ trans('admin.reviews') }}</span>
                    </a>
                </li>
                <li>
                    <a href="{{ url('terms') }}" target="_blank" class="">
                        <i class="mdi mdi-settings fa-fw"></i>
                        <span class="">{{ trans('admin.terms') }}</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('teacher.edit',[auth()->user()->id]) }}" target="_blank" class="">
                        <i class="mdi mdi-settings fa-fw"></i>
                        <span class="">{{ trans('admin.setting') }}</span>
                    </a>
                </li>
            @endif

            @if(auth()->user()->role==1)
                <li>
                    <a href="{{ route('subject.index') }}" class="">
                        <i class="mdi mdi-settings fa-fw"></i>
                        <span class="">{{ trans('admin.subject') }}</span>
                    </a>
                </li>

                <li>
                    <a href="index.html" class="waves-effect">
                        <i class="mdi mdi-av-timer fa-fw" data-icon="v"></i>
                        <span class="hide-menu">
                        {{ trans('admin.landpage') }}
                            <span class="fa arrow"></span>
                        <span class="label label-rouded label-info pull-right">4</span>
                    </span>
                    </a>

                    <ul class="nav nav-second-level">
                        <li>
                            <a href="{{ route('landpage.home') }}">
                                <i class=" fa-fw"></i>
                                <span class="hide-menu">{{ trans('landpage.home') }}</span>
                            </a>
                        </li>

                        <li>
                            <a href="{{ route('landpage.feature') }}">
                                <i class=" fa-fw"></i>
                                <span class="hide-menu">{{ trans('landpage.features') }}</span>
                            </a>
                        </li>

                        <li>
                            <a href="{{ route('landpage.awesomefeature') }}">
                                <i class=" fa-fw"></i>
                                <span class="hide-menu">{{ trans('landpage.awesome_feature') }}</span>
                            </a>
                        </li>

                        <li>
                            <a href="{{ route('landpage.about') }}">
                                <i class=" fa-fw"></i>
                                <span class="hide-menu">{{ trans('landpage.about') }}</span>
                            </a>
                        </li>

                        <li>
                            <a href="{{ route('screenshot.index') }}" class="waves-effect">
                                <i class=" fa-fw"></i>
                                <span class="hide-menu">{{ trans('landpage.screenshot') }}</span>
                            </a>
                        </li>

                        <li>
                            <a href="{{ route('team.index') }}" class="waves-effect">
                                <i class=" fa-fw"></i>
                                <span class="hide-menu">{{ trans('landpage.team') }}</span>
                            </a>
                        </li>

                        <li>
                            <a href="{{ route('testimonials.index') }}">
                                <i class=" fa-fw"></i>
                                <span class="hide-menu">{{ trans('landpage.testimonials') }}</span>
                            </a>
                        </li>

                        <li>
                            <a href="{{ route('faq.index') }}">
                                <i class=" fa-fw"></i>
                                <span class="hide-menu">{{ trans('landpage.faqs') }}</span>
                            </a>
                        </li>

                        <li>
                            <a href="{{ route('landpage.general') }}">
                                <i class=" fa-fw"></i>
                                <span class="hide-menu">{{ trans('landpage.general') }}</span>
                            </a>
                        </li>


                    </ul>
                </li>

                <li class="devider"></li>

                <li>
                    <a href="{{ route('teacher.index') }}" class="waves-effect">
                        <i class="mdi mdi-settings fa-fw"></i>
                        <span class="hide-menu">{{ trans('admin.teacher') }}</span>
                    </a>
                </li>


                <li>
                    <a href="{{ route('student.index') }}" class="waves-effect">
                        <i class="mdi mdi-settings fa-fw"></i>
                        <span class="hide-menu">{{ trans('admin.student') }}</span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('certificate.index') }}" class="waves-effect">
                        <i class="mdi mdi-settings fa-fw"></i>
                        <span class="hide-menu">{{ trans('login.certificate') }}</span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('education.index') }}" class="waves-effect">
                        <i class="mdi mdi-settings fa-fw"></i>
                        <span class="hide-menu">{{ trans('admin.education_level') }}</span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('grade.index') }}" class="waves-effect">
                        <i class="mdi mdi-settings fa-fw"></i>
                        <span class="hide-menu">{{ trans('admin.grade') }}</span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('slider.index') }}" class="waves-effect">
                        <i class="mdi mdi-settings fa-fw"></i>
                        <span class="hide-menu">{{ trans('admin.slider') }}</span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('relation.index') }}" class="waves-effect">
                        <i class="mdi mdi-settings fa-fw"></i>
                        <span class="hide-menu">{{ trans('admin.relation') }}</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('religion.index') }}" class="waves-effect">
                        <i class="mdi mdi-settings fa-fw"></i>
                        <span class="hide-menu">{{ trans('admin.religion') }}</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('job.index') }}" class="waves-effect">
                        <i class="mdi mdi-settings fa-fw"></i>
                        <span class="hide-menu">{{ trans('admin.job') }}</span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('category.index') }}" class="waves-effect">
                        <i class="mdi mdi-settings fa-fw"></i>
                        <span class="hide-menu">{{ trans('admin.category') }}</span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('subcategory.index') }}" class="waves-effect">
                        <i class="mdi mdi-settings fa-fw"></i>
                        <span class="hide-menu">{{ trans('admin.subcategory') }}</span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('package.index') }}" class="waves-effect">
                        <i class="mdi mdi-settings fa-fw"></i>
                        <span class="hide-menu">{{ trans('admin.package') }}</span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('landpage.contact') }}" class="waves-effect">
                        <i class="mdi mdi-settings fa-fw"></i>
                        <span class="hide-menu">{{ trans('admin.contact') }}</span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('landpage.subscribe') }}" class="waves-effect">
                        <i class="mdi mdi-settings fa-fw"></i>
                        <span class="hide-menu">{{ trans('admin.subscribe') }}</span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('admin.setting') }}" class="waves-effect">
                        <i class="mdi mdi-settings fa-fw"></i>
                        <span class="hide-menu">{{ trans('admin.setting') }}</span>
                    </a>
                </li>
            @endif


        </ul>
    </div>
</div>